export const siteConfig = {
  identity: {
    displayName: 'MONTES',
    footerDomain: 'MONTES.WORK ☮︎',
    domain: 'montes.work',
    location: 'NEW YORK CITY / GLOBAL',
    email: 'hello@montes.work',
    phone: '+1 (NYC) — AVAILABLE UPON REQUEST',
    linkedin: 'https://www.linkedin.com/in/eli-montes-dataanalyst',
    copyrightYear: '2026',
    estYear: '2016',
    motifSymbol: '☮︎',
  },
  meta: {
    title: 'MONTES.WORK — Still, Motion & Projects',
    description:
      'MONTES is a New York City visual-content, creative-production, and project-management professional working across still photography, motion, project-led live work, and event documentation.',
    openGraphTitle: 'MONTES.WORK — Still, Motion & Projects',
    openGraphDescription:
      'Visual storytelling for the real world — still, motion, and project-led work from New York City.',
  },
  navLinks: [
    { label: '00 — RÉPERTOIRE', href: '#repertoire', number: '00' },
    { label: '001 — STILL', href: '#still', number: '001' },
    { label: '002 — MOTION', href: '#motion', number: '002' },
    { label: '003 — PROJECTS', href: '#projects', number: '003' },
    { label: '004 — CONTACT', href: '#contact', number: '004' },
  ],
  section00: {
    indexLabel: '00 — RÉPERTOIRE',
    heroTitle: 'MONTES',
    mainStatement: 'VISUAL STORYTELLING FOR THE REAL WORLD.',
    supportingLine: 'STILL — MOTION — PROJECTS / NEW YORK CITY',
    narrativeParagraphs: [
      'Built in major-agency settings and refined through live work, his practice moves between the image and the operation behind it: creative direction and content capture, stakeholder alignment, and client-facing delivery.',
      'He approaches every assignment with equal attention to visual clarity, cultural context, production realities, and the audience on the other side of the work—executing public-facing campaigns, live activations, and content delivery across fashion, beauty, technology, and culture.',
    ],
    agencyLabel: 'AGENCY EXPERIENCE —',
    agencies: 'TBWA\\CHIAT\\DAY — HAVAS — CNC AGENCY',
    brandLabel: 'SELECTED BRAND EXPERIENCE —',
    brands:
      'APPLE — NIKE — FUJIFILM — BOTTEGA VENETA — UBER — PRADA — GAP — NETFLIX — MAC — BOSE — YSL — DAVID YURMAN — KITH — TIFFANY & CO. — CHANEL — NOTION',
    domainExpertiseLabel: 'DOMAIN EXPERTISE —',
    domainExpertiseList: [
      'CREATIVE PRODUCTION',
      'PROJECT MANAGEMENT',
      'ACTIVATIONS',
      'LIVE EVENTS',
      'CLIENT SUCCESS',
      'CONTENT DELIVERY',
    ],
    placeholderLabel: 'NYC VISUAL PLACEHOLDER — TO BE REPLACED',
  },
  section001: {
    sectionLabel: '001 — STILL',
    largeHeadline: 'PEOPLE. PLACE. THE MOMENT BETWEEN.',
    body: 'Photography that documents the energy, people, and texture of a moment—from public-facing events and activations to editorial, behind-the-scenes, product concepts, and environmental coverage.',
    placeholderLabel: 'SELECTED STILL WORK',
    smallMetadata: 'STILL PHOTOGRAPHY ARCHIVE',
    stills: [
      {
        id: 'anua-dew-popup',
        label: 'ANUA — DEW ON THE GO (SOHO POP-UP)',
        metadata: 'ANUA × CNC — BEAUTY & EVENT COVERAGE',
        imageSrc: '/images/still/anua/anua-1.jpg',
        gallery: [
          '/images/still/anua/anua-1.jpg',
          '/images/still/anua/anua-2.jpg',
          '/images/still/anua/anua-3.jpg',
        ],
        altText: 'ANUA Dew On The Go SoHo pop-up installation featuring Kendall Jenner',
      },
      {
        id: 'notion-hero',
        label: 'MAKE WITH NOTION — ANNUAL CONFERENCE',
        metadata: 'NOTION × CNC — EVENT COVERAGE',
        imageSrc: '/images/still/notion/notion-1.jpg',
        gallery: [
          '/images/still/notion/notion-1.jpg',
          '/images/still/notion/notion-2.jpg',
          '/images/still/notion/notion-3.jpg',
          '/images/still/notion/notion-4.jpg',
        ],
        altText: 'Make with Notion annual user conference keynote stage presentation photography',
      },
      {
        id: 'bose-butter-hero',
        label: 'BOSE — BUTTERMANIA SOUNDLINK PLUS',
        metadata: 'BOSE × CNC — PRODUCT & MERCH CONCEPT',
        imageSrc: '/images/still/bose/bose-1.jpg',
        gallery: [
          '/images/still/bose/bose-1.jpg',
          '/images/still/bose/bose-2.jpg',
          '/images/still/bose/bose-3.jpg',
          '/images/still/bose/bose-4.jpg',
        ],
        altText: 'Bose SoundLink Plus Buttermania custom packaging photography',
      },
      {
        id: 'mac-nudes-hero',
        label: 'M·A·C — I ONLY WEAR M·A·C (SOHO TAKEOVER)',
        metadata: 'M·A·C × CNC — BEAUTY & EVENT STILLS',
        imageSrc: '/images/still/mac/mac-1.jpg',
        gallery: [
          '/images/still/mac/mac-1.jpg',
          '/images/still/mac/mac-2.jpg',
          '/images/still/mac/mac-3.jpg',
          '/images/still/mac/mac-4.jpg',
        ],
        altText: 'M·A·C Cosmetics SoHo flagship takeover event photography',
      },
    ],
  },
  section002: {
    sectionLabel: '002 — MOTION',
    largeHeadline: 'MOMENTUM HAS A POINT OF VIEW.',
    body: 'Short-form video, event documentation, interviews, behind-the-scenes capture, and social-first storytelling.',
    placeholderLabel: 'SELECTED MOTION REELS',
    smallMetadata: '9:16 VERTICAL MOTION ARCHIVE',
    reels: [
      {
        id: 'reel-1',
        title: 'NIKE — NIKE GRIND (SUSTAINABILITY CAFÉ)',
        metadata: 'NIKE × CNC — 9:16 VERTICAL MOTION',
        videoSrc: '/videos/nike-grind.mp4',
        poster: '/images/projects/nike-grind/hero.jpg',
        summary:
          'Nike partnered with CNC to transform an NYC space into an immersive sustainability café celebrating Nike Grind recycled material technology.',
      },
      {
        id: 'reel-2',
        title: 'REEL 02 — BRANDED CONTENT & PRODUCT MOTION',
        metadata: '9:16 VERTICAL REEL — PRODUCT & MERCH',
        videoSrc: '',
        poster: '/images/still/bose/bose-1.jpg',
        summary:
          'Tactile product details, merch reveals, and editorial video storytelling designed for social-first delivery.',
      },
      {
        id: 'reel-3',
        title: 'REEL 03 — BEHIND THE SCENES & STAGE DIRECTING',
        metadata: '9:16 VERTICAL REEL — PRODUCTION & BTS',
        videoSrc: '',
        poster: '/images/still/notion/notion-1.jpg',
        summary:
          'On-site creative production, keynote stage directing, crew coordination, and real-world execution footage.',
      },
    ],
  },
  section003: {
    sectionLabel: '003 — PROJECTS',
    largeHeadline: 'FROM BRIEF TO REAL WORLD.',
    body: 'Project-led support for live activations, public-facing work, and content delivery—bringing together creative teams, client needs, timelines, stakeholder communication, on-site coordination, and the details that make work land.',
    metadata:
      'ACTIVATIONS — LIVE EVENTS — CLIENT SUCCESS — PROJECT MANAGEMENT — CONTENT CAPTURE — ON-SITE EXECUTION — DELIVERY',
    placeholderLabel: 'SELECTED PROJECTS — FORTHCOMING',
    projectsList: [
      {
        id: 'bottega-veneta-cafe',
        title: 'BOTTEGA VENETA — MADISON AVE NYFW CAFÉ',
        client: 'BOTTEGA VENETA × CNC AGENCY',
        category: 'RETAIL ACTIVATION / NYFW',
        metrics: '10M+ SOCIAL IMPRESSIONS — 1K+ CUSTOMERS SERVED',
        imageSrc: '/images/projects/bottega-veneta/hero.png',
        objectPosition: 'object-center',
        gallery: [
          '/images/projects/bottega-veneta/hero.png',
          '/images/projects/bottega-veneta/cafe-1.jpg',
          '/images/projects/bottega-veneta/latte-art.jpg',
          '/images/projects/bottega-veneta/exterior.jpg',
        ],
        summary:
          'Bottega Veneta transformed its Madison Avenue flagship boutique into an in-store café during New York Fashion Week. CNC Agency crafted a minimalist experience where guests customized Bottega branded lattes, explored the new collection, and captured content.',
      },
      {
        id: 'prada-virtual-flower',
        title: 'PRADA — PARADOXE VIRTUAL FLOWER',
        client: 'PRADA × CNC AGENCY',
        category: 'MOBILE VEHICLE / NYFW',
        metrics: '18K+ FLORAL STEMS — 14K SAMPLES — 3 POP-UPS',
        imageSrc: '/images/projects/prada/hero.jpg',
        objectPosition: 'object-bottom',
        gallery: [
          '/images/projects/prada/hero.jpg',
          '/images/projects/prada/lab-1.jpg',
          '/images/projects/prada/lab-2.jpg',
          '/images/projects/prada/lab-3.jpg',
        ],
        summary:
          'Prada’s Paradoxe Virtual Flower arrived during New York Fashion Week with a roaming floral installation—a mint green flower lab that brought Prada’s modern femininity into the streets through couture-level blooms and a fragrance discovery experience.',
      },
      {
        id: 'loreal-ppd-protege',
        title: 'L’ORÉAL — PPD PROTÉGÉ PROGRAM',
        client: 'L’ORÉAL × CNC AGENCY',
        category: 'MULTIDAY IMMERSION / BEAUTY',
        metrics: '60+ PRODUCT DISPLAYS — 150-PERSON LAUNCH PARTY',
        imageSrc: '/images/projects/loreal/hero.jpg',
        objectPosition: 'object-center',
        gallery: [
          '/images/projects/loreal/hero.jpg',
          '/images/projects/loreal/lab-1.jpg',
          '/images/projects/loreal/lab-2.jpg',
          '/images/projects/loreal/lab-3.jpg',
        ],
        summary:
          'L’Oréal Professional Products Division launched its inaugural Protégé Program with a multiday influencer immersion in Los Angeles. CNC designed a custom ProLAB, shoppable School Store, 60+ product displays, and a 150-person launch party.',
      },
      {
        id: 'ysl-essence-fest',
        title: 'YSL BEAUTY — MYSLF L’ABSOLU (ESSENCE FEST)',
        client: 'YSL BEAUTY × CNC AGENCY',
        category: 'FESTIVAL POP-UP / BEAUTY',
        metrics: '16K+ ATTENDEES — 16K+ SAMPLES — 1K PHOTOBOOTH',
        imageSrc: '/images/projects/ysl-essence/hero.jpg',
        objectPosition: 'object-center',
        gallery: [
          '/images/projects/ysl-essence/hero.jpg',
          '/images/projects/ysl-essence/lab-1.jpg',
          '/images/projects/ysl-essence/lab-2.jpg',
          '/images/projects/ysl-essence/lab-3.jpg',
        ],
        summary:
          'YSL Beauty introduced the MYSLF L’Absolu fragrance at Essence Fest with a 20×30 pop-up sensory brand world where guests explored key notes through immersive displays, fragrance sampling, and mirrored campaign visuals.',
      },
    ],
  },
  section004: {
    sectionLabel: '004 — CONTACT',
    largeHeadline: 'LET’S MAKE THE WORK LAND.',
    body: 'Available globally for stills, motion, event documentation, project-led support, and creative-production coordination.',
    metadata: 'NEW YORK CITY / GLOBAL — AVAILABLE FOR SELECT ASSIGNMENTS',
    formTitle: 'SEND A MESSAGE —',
    submitText: 'SEND A BRIEF →',
    confirmationCopy: 'BRIEF RECEIVED — STANDING BY.',
  },
};
